### ISSUE TITLE
Twitter client occasionally closes stream and does not reconnect

### ISSUE THREAD

**Issue by cat-haines** [electricimp/Twitter#2]
> [IoCowbell](https://gist.github.com/anonymous/d50e41b391870814c3e7) stopped it's stream with a "Stream Closed (52: )" and did not resume streaming. Looking at the code, any return value which is not 28, 200 or 420 will trigger this behavior, without ever calling an error handler.
> 
> As a user I expect that the Twitter class will make a best effort to keep my stream open unless I specify an onError handler, in which cases unknown errors should be reported.
> 
> \- @bbharris

**Comment by blindman2k** [comment]
This looks like a resolved issue now.
If you have an onError() handler its up to you to reconnect. If you don't then the class will immediately reconnect after any error.
